### ISSUE TITLE
Typo3 v10 and Time based blocking

### ISSUE THREAD

**Issue by MediKathi** [cepheiVV/block_malicious_login_attempts#1]
Hello,

this is nice and helpful extension.

But in order to get this work with Typo3 v10 I had to translate the query in the BlockedIpController.php into the querybuilder noation.

Also I though a Time-Based Blocking would be nice, if a User just misstype the password once a day.

Here my example:
Change the Query given in the `BlockedIpController.php` file.
```php
...
    public function indexAction()
    {
        $extensionConfiguration = GeneralUtility::makeInstance(ExtensionConfiguration::class)->get('block_malicious_login_attempts');
        $failedLoginLimit = $extensionConfiguration["failedLoginLimit"];
        $failedLoginTime = $extensionConfiguration["failedLoginTime"];

        // get all IP's that reached the limit
        $table = "tx_blockmaliciousloginattempts_failed_login";
        $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable($table);
        $ipList = $queryBuilder->select('ip')
            ->addSelectLiteral('COUNT(ip) as count')
            ->addSelectLiteral('COUNT(ip) >= "'.$failedLoginLimit.'" as blocked')
            ->from($table)
            ->where(
                $queryBuilder->expr()->gte('time', (time()-$failedLoginTime) )
            )
            ->groupBy('ip')
            ->execute()->fetchAll();


        $this->view->assign("ipList", $ipList);
        $this->view->assign("failedLoginLimit", $failedLoginLimit);
        $this->view->assign("currentPage", "index");
    }
...
```

I also made adjustments to the `BlockMaliciousLoginAttempts.php` file:
```php
...
    /**
     * check whether the ip is blocked
     *
     * @param $ip
     * @return bool
     */
    protected function testIpAgainstMaliciousIpList($ip): bool
    {
        $failedLoginLimit = $this->getFailedLoginLimit();
        $failedLoginTime = $this->getFailedLoginTime();
        
        $table = "tx_blockmaliciousloginattempts_failed_login";
        $queryBuilder = GeneralUtility::makeInstance(
            ConnectionPool::class
        )->getQueryBuilderForTable($table);

        $attemptedLogins = $queryBuilder
            ->count('uid')
            ->from($table)
            ->where(
                $queryBuilder->expr()->eq('ip', $queryBuilder->createNamedParameter($ip))
            )
            ->andWhere(
                $queryBuilder->expr()->gte('time', (time()-$failedLoginTime) )
            )
            ->execute()
            ->fetchColumn(0);

        return $attemptedLogins >= $failedLoginLimit;
    }
...
    /**
     * @return int
     */
    protected function getFailedLoginTime(): int
    {
        $failedLoginTime = $this->extensionConfiguration["failedLoginTime"] ?? (24*3600);
        return (int)$failedLoginTime;
    }
```

Added the default time to the `ext_conf_template.txt`
```
...
# cat=basic/enable/050; type=int; label=Max IP Age
failedLoginTime = 86400
...
```

To autoload the Typoscript, I added a `ext_localconf.php` with this content:
```php
<?php
defined('TYPO3') or die();

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScriptSetup(file_get_contents(\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('block_malicious_login_attempts', 'Configuration/TypoScript/setup.typoscript')));
```

**Comment by cepheiVV** [comment]
Hi. Thanks for your suggestions.

> But in order to get this work with Typo3 v10 
Was there an error?

I would add the time-based blocking if it can be deactivated.
Mabe setting `failedLoginTime = 0` to deactivate this feature?

Would you mind adding this as a PR?

**Comment by MediKathi** [comment]
> Hi. Thanks for your suggestions.
> 
> > But in order to get this work with Typo3 v10
> > Was there an error?
> 
> I would add the time-based blocking if it can be deactivated. Mabe setting `failedLoginTime = 0` to deactivate this feature?
> 
> Would you mind adding this as a PR?

The error was a Method not found
Before typo3 v11.5 there was/is no `executeQuery` method.
> Changed in version 11.5: The widely used function ->execute() has been split into the methods executeQuery and executeStatement(). executeQuery returns a \Doctrine\DBAL\Result instead of a \Doctrine\DBAL\Statement.
Source: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Database/QueryBuilder/Index.html#execute-executequery-and-executestatement

Pullrequest in the making

**Comment by cepheiVV** [comment]
Thanks for the PR!

Merged your changes. Made a few text adjustments and set the version to 1.6.0.
You can "composer update" to get the new version.
